name: Build

on:
  workflow_call:
    secrets:
      docker_username:
        required: false
      docker_password:
        required: false
    inputs:
      golang_version:
        default: '1.21'
        required: false
        type: string
      app_name:
        required: false
        type: string
      version:
        type: string
        required: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.golang_version }}
      - name: Check out code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        if: ${{ inputs.version }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_password }}
      - name: Install dependencies
        run: go mod vendor
      - name: Build
        if: ${{ !inputs.version }}
        run: make build
      - name: Set up Docker Buildx
        if: ${{ inputs.version }}
        uses: docker/setup-buildx-action@v3
      - name: Docker build and push
        id: docker-build-and-push
        if: ${{ inputs.version }}
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7 \
            --build-arg "VERSION=${{ inputs.version }}" \
            -t aukilabs/${{ inputs.app_name }}:latest \
            -t aukilabs/${{ inputs.app_name }}:${{ github.sha }} \
            -t aukilabs/${{ inputs.app_name }}:${{ inputs.version }} \
            --push \
            .
