name: Build

on: [push]

jobs:
  codecheck:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Configure GitHub For Private Modules
        env:
          GOPRIVATE: "github.com/aukilabs/*"
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GH_PAT }}
        run: git config --global url."https://aukilabs:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Vet
        run: go vet ./...

  tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Configure GitHub For Private Modules
        env:
          GOPRIVATE: "github.com/aukilabs/*"
          GITHUB_TOKEN: ${{ secrets.GLOBAL_GH_PAT }}
        run: git config --global url."https://aukilabs:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: go mod download
      - name: Tests
        run: go test ./...
