name: Tests

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    name: Tests
    with:
      enable_coverage: true
  custom:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "the ref: ${{ github.ref_name }}"
          echo "more echo"

