name: Tests

on: [push]

jobs:
  codecheck:
    name: Run code check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Vet
        run: go vet ./...

  tests:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: go mod download
      - name: Tests
        run: go test ./...
