name: Tests

on: [push]

jobs:
  codecheck:
    name: Run code check
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Vet
        run: go vet ./...

  tests:
    name: Run test suite
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: go mod download
      - name: Tests
        run: go test ./...
